### ISSUE TITLE
A blank example.env would be incredibly helpful

### ISSUE THREAD

**Issue by michaeljhopkins** [AndersSchmidtHansen/LaravelSidequest#2]
There are a lot of places that reference env variables. A lot of them are standard (database, debug etc) however to up confidence I made all the necessary variables, a blank `example.env` file would be very very helpful

**Comment by AndersSchmidtHansen** [comment]
Hi Michael!

I'll get right to it :) and thanks for letting me know!

**Comment by AndersSchmidtHansen** [comment]
I added an `.env.example` file from the original Laravel source now, hope this works. :)
