### ISSUE TITLE
Expiration text box breaks ability to subscribe

### ISSUE THREAD

**Issue by michaeljhopkins** [AndersSchmidtHansen/LaravelSidequest#3]
The expiration date text box forces a `/` into the text. Stripe's api doesn't like this so much

**Comment by AndersSchmidtHansen** [comment]
Hmmm, I'll check it out and get right back to you. It must have something to do with me adding jQuery.Payments to the project :)

**Comment by AndersSchmidtHansen** [comment]
This should now be fixed @michaeljhopkins :) Try giving it a spin
